### ISSUE TITLE
Question about n_feat value

### ISSUE THREAD

**Issue by baehaeli** [Sowmya-R-Krishnan/RSAPred#2]
I have a question about the n_feat value used in 'ffs_final.py'. The README does not clearly define how to set the n_feat value.

https://github.com/Sowmya-R-Krishnan/RSAPred/blob/03fbc3fb9600986f2680ab1bffe01630a4a5d35d/Feature_selection/ffs_final.py#L24

When setting n_feat to 2, the ffs_final.py code runs, but the process_regression_output_v1.py code gives p1 and p2 values of 0, and the get_desc_stats_v1.py file does not run because there is no column in the process_regression_output_v1.py code output file.

When setting n_feat to 3, the ffs_final.py code does not finish running.

Could you please provide guidelines on how to appropriately set the n_feat hyperparameter? Specifically, what is the recommended value for n_feat in RSAPred dataset?

Thank you for your assistance.

**Comment by Sowmya-R-Krishnan** [comment]
Hi. Thanks for the message. The n_feat value indicates the number of features to be considered for the combination. So by setting n_feat = 2, you are computing all possible 2 feature combinations and n_feat = 3, you are computing all possible 3 feature combinations. Technically, the code can compute any number of feature combinations (n_feat value can be anything), but the runtime will increase proportionately.
By using n_feat = 2 and pass_feat = "all", the program will compute all possible 2 feature combinations, which will not take a lot of time. But with n_feat = 3 and pass_feat = "all", it will take a while to finish, even though we have parallelized the code with "multi-processing" package. I suggest you change the Pool(4) parameter in line 86 to the desirable number of processes you can use - more the number of processes, faster the code will execute.

Also, for n_feat > 3, you can try supplying the first output of get_desc_stats_v1.py instead of "all" for the pass_feat parameter. That will reduce the number of features to consider for computing the "n" feature combinations, thereby decreasing the runtime significantly. Hope this clarifies - let me know if you have any further queries.

With regards,
Sowmya

**Comment by baehaeli** [comment]
Thank you for answering my question.
I run the code using the "./data/Aptamers_dataset_v1.csv" dataset.
The Data_processing codes and ffs_final.py code executed successfully with n_feat=2. 
However when I run the process_regression_output_v1.py file, I get '0 0' output and encountered an error in get_desc_stats_v1.py file.

Could you please provide the n_feat hyperparameter value for each rna type that you used in the research paper?

I share the output files with aptamer data.
[output_aptamer.zip](https://github.com/Sowmya-R-Krishnan/RSAPred/files/15413115/output_aptamer.zip)

**Comment by Sowmya-R-Krishnan** [comment]
Hi. We used forward feature selection - so for every RNA subtype the code was executed from n_feat = 2 till the final number of features reported in the [paper](https://doi.org/10.1093/bib/bbae002) (Refer Table 2 column 2 for n_feat values and Table 3 for the complete list of features for each type).

When running process_regression_output_v1.py, you should change the correlation cut-off used for filtering the best models. From the outputs you have provided, the maximum correlation is 0.45 and the cut-off in the code is 0.60. So none of the models have passed the filter and the subsequent code (get_desc_stats_v1.py) throws an error. Please change the cut-off and try again. I will also update this in the README file for clarity.

**Comment by baehaeli** [comment]
Thank you for your kind answers.

I apologize for the continued questions. I have another question about handling multicollinearity.

Where can I find the code for addressing multicollinearity?

In my understanding, the ffs_final.py code does not calculate correlations between features. Instead, it evaluates the regression model's performance using different feature combinations and the target variable (pKd value). It seems to focus on feature selection based on predictive performance rather than explicitly removing multicollinearity by analyzing feature correlations.

https://github.com/Sowmya-R-Krishnan/RSAPred/blob/e2d34e4837604db9b0e87d3eb16116049025337b/Feature_selection/ffs_final.py#L87

I would greatly appreciate your clarification on this.

**Comment by Sowmya-R-Krishnan** [comment]
While running ffs_final.py, we have provided an input file named - Pairwise_featcorr_0.8.pkl. This file contains all pairwise feature correlations which pass our pairwise correlation threshold (r<0.8).
In the ffs_final.py code, lines 74-79 are designed to handle multi-collinearity. For every possible feature combination with n_feat features, first we check if all the feature pairs within the combination have r<0.8. **Only if all feature pairs pass this criteria (no multi-collinearity), they are used to build a regression model**. Hope this clarifies.

```
if(n>2):
	feat_combinations_pass = []
	for combination in feat_combinations:
		feat_pairs = set(list(combinations(combination, 2)))  #Creates all possible pairs of n_feat features in a combination
		feat_pass = [True for pair in feat_pairs if(pair in pair_corrs)]  #Checks if each pair passes the r<0.8 cut-off
		if(len(feat_pass)==len(feat_pairs)):  #Only if all pairs pass (no multi-collinearity), the combination is used for model
			feat_combinations_pass.append(combination)
```

Pairwise_featcorr_0.8.pkl has been provided so that the calculation of pairwise correlations is not repeated again and again. This will save time in building the actual feature combinations. For a detailed description of this process, check: https://pubs.acs.org/doi/10.1021/acs.jmedchem.2c00254 - Data refinement section.

**Comment by baehaeli** [comment]
Thank you so much for your detailed explanation and clarification. I now understand how the code handles multicollinearity by using the Pairwise_featcorr_0.8.pkl file to filter feature combinations based on pairwise correlations. Your response and the reference to the publication have been very helpful. I appreciate your time and support.

Best regards,

Haelee Bae
